---
- name: Upload Config | Kibana
  template:
    src: config/kibana.yml
    dest: /opt/kibana/kibana-{{ kibana_version }}-linux-{{ kibana_arch }}/config/kibana.yml
  tags:
    - configuration
    - template-configuration
    - kibana
